### ISSUE TITLE
page is always loading

### ISSUE THREAD

**Issue by TwinkleLeon** [BuilderIO/figma-html#84] opened 2021-11-01 07:54 UTC
when i get code from html-to-figma plugin dialog

![image](https://user-images.githubusercontent.com/26670694/139639515-a021509c-1fd4-4b18-8081-e26673362755.png)

the page is always loading

![preview](https://user-images.githubusercontent.com/26670694/139639081-aad5fa14-c50d-44af-9203-21ce6cb31ba7.jpg)

and i found that this api was timeout, is it cause by this ?

![image](https://user-images.githubusercontent.com/26670694/139639346-cca36cb2-ecb6-4f59-b357-0cc865852100.png)

**Comment by zhigang1992** [comment] 2021-11-19 15:49
![image](https://user-images.githubusercontent.com/1057756/142651281-93d7af76-8e4f-401f-afbb-4c18aefde7cf.png)

We are getting something like this

```
[2021-11-19T15:48:36.508Z]  @firebase/firestore: Firestore (8.2.7): INTERNAL UNHANDLED ERROR:  TypeError: Cannot use 'in' operator to search for 'nullValue' in null
```

**Comment by zhigang1992** [comment] 2021-11-19 15:55
It worked after I created an account on builder.io and signed in.

**Comment by steve8708** [comment] 2021-11-19 17:09
ah, thanks for that useful info @zhigang1992 - this explains why we have struggled to reproduce! Looking into it now

**Comment by steve8708** [comment] 2021-11-22 18:43
Found the cause here and just pushed the fix! Please let us know if you run into any other issues or if things do not work as expected for you

**Closed by steve8708** 2021-11-22 18:43 UTC
